name 'zack-report'
version '1.0.0'
source 'git://github.com/acidprime/puppet-report.git'
author 'Zack Smith'
license 'Apache'
summary 'Puppet face for querying puppetdb reports'
description 'Query all nodes puppetdb exports'
project_page 'http://github.com/acidprime/puppet-report'
